# GNOME dconf settings
# Apply with: dconf load / < gnome/dconf-settings.ini

[org/gnome/desktop/input-sources]
current=uint32 0
sources=[('xkb', 'us')]
xkb-options=['caps:swapescape']

[org/gnome/desktop/interface]
accent-color='slate'
color-scheme='prefer-dark'
cursor-size=24
enable-animations=true
enable-hot-corners=true
gtk-theme='Adwaita'
icon-theme='Adwaita'
overlay-scrolling=true
toolkit-accessibility=false

[org/gnome/desktop/peripherals/keyboard]
numlock-state=true

[org/gnome/desktop/session]
idle-delay=uint32 600

[org/gnome/desktop/wm/keybindings]
move-to-monitor-down=['<Super><Shift>Down']
move-to-monitor-left=['<Super><Shift>Left']
move-to-monitor-right=['<Super><Shift>Right']
move-to-monitor-up=['<Super><Shift>Up']
move-to-workspace-down=['<Control><Shift><Alt>Down']
move-to-workspace-left=['<Super><Shift>Page_Up', '<Super><Shift>KP_Prior', '<Super><Shift><Alt>Left', '<Control><Shift><Alt>Left']
move-to-workspace-right=['<Super><Shift>Page_Down', '<Super><Shift>KP_Next', '<Super><Shift><Alt>Right', '<Control><Shift><Alt>Right']
move-to-workspace-up=['<Control><Shift><Alt>Up']
switch-applications=['<Super>Tab', '<Alt>Tab']
switch-applications-backward=['<Shift><Super>Tab', '<Shift><Alt>Tab']
switch-group=['<Super>Above_Tab', '<Alt>Above_Tab']
switch-group-backward=['<Shift><Super>Above_Tab', '<Shift><Alt>Above_Tab']
switch-panels=['<Control><Alt>Tab']
switch-panels-backward=['<Shift><Control><Alt>Tab']
switch-to-workspace-1=['<Super>Home']
switch-to-workspace-last=['<Super>End']
switch-to-workspace-left=['<Super>Page_Up', '<Super>KP_Prior', '<Super><Alt>Left', '<Control><Alt>Left']
switch-to-workspace-right=['<Super>Page_Down', '<Super>KP_Next', '<Super><Alt>Right', '<Control><Alt>Right']

[org/gnome/desktop/wm/preferences]
action-middle-click-titlebar='minimize'
button-layout='appmenu:close'

[org/gnome/mutter]
attach-modal-dialogs=true
edge-tiling=false
workspaces-only-on-primary=true

[org/gnome/mutter/keybindings]
cancel-input-capture=['<Super><Shift>Escape']

[org/gnome/mutter/wayland/keybindings]
restore-shortcuts=['<Super>Escape']

[org/gnome/Ptyxis]
audible-bell=false
interface-style='system'
restore-session=false
restore-window-size=false
visual-bell=false

[org/gnome/settings-daemon/plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Super>Return'
command='ptyxis'
name='Open Terminal'

[org/gnome/shell]
disable-user-extensions=false
enabled-extensions=['forge@jmmaranan.com', 'just-perfection-desktop@just-perfection', 'AlphabeticalAppGrid@stuarthayhurst', 'blur-my-shell@aunetx']
favorite-apps=@as []

[org/gnome/shell/extensions/blur-my-shell]
settings-version=2

[org/gnome/shell/extensions/blur-my-shell/appfolder]
brightness=0.59999999999999998
sigma=30

[org/gnome/shell/extensions/blur-my-shell/coverflow-alt-tab]
pipeline='pipeline_default'

[org/gnome/shell/extensions/blur-my-shell/dash-to-dock]
blur=true
brightness=0.59999999999999998
pipeline='pipeline_default_rounded'
sigma=30
static-blur=true
style-dash-to-dock=0

[org/gnome/shell/extensions/blur-my-shell/lockscreen]
pipeline='pipeline_default'

[org/gnome/shell/extensions/blur-my-shell/overview]
pipeline='pipeline_default'

[org/gnome/shell/extensions/blur-my-shell/panel]
brightness=0.59999999999999998
pipeline='pipeline_default'
sigma=30

[org/gnome/shell/extensions/blur-my-shell/screenshot]
pipeline='pipeline_default'

[org/gnome/shell/extensions/blur-my-shell/window-list]
brightness=0.59999999999999998
sigma=30

[org/gnome/shell/extensions/forge]
css-last-update=uint32 37

[org/gnome/shell/extensions/forge/keybindings]
con-split-horizontal=['<Super>z']
con-split-layout-toggle=['<Super>g']
con-split-vertical=['<Super>v']
con-stacked-layout-toggle=['<Shift><Super>s']
con-tabbed-layout-toggle=['<Shift><Super>t']
con-tabbed-showtab-decoration-toggle=['<Control><Alt>y']
focus-border-toggle=['<Super>x']
prefs-tiling-toggle=['<Super>w']
window-focus-down=['<Super>j']
window-focus-left=['<Super>h']
window-focus-right=['<Super>l']
window-focus-up=['<Super>k']
window-gap-size-decrease=['<Control><Super>minus']
window-gap-size-increase=['<Control><Super>plus']
window-move-down=['<Shift><Super>j']
window-move-left=['<Shift><Super>h']
window-move-right=['<Shift><Super>l']
window-move-up=['<Shift><Super>k']
window-resize-bottom-decrease=['<Shift><Control><Super>i']
window-resize-bottom-increase=['<Control><Super>u']
window-resize-left-decrease=['<Shift><Control><Super>o']
window-resize-left-increase=['<Control><Super>y']
window-resize-right-decrease=['<Shift><Control><Super>y']
window-resize-right-increase=['<Control><Super>o']
window-resize-top-decrease=['<Shift><Control><Super>u']
window-resize-top-increase=['<Control><Super>i']
window-snap-center=['<Control><Alt>c']
window-snap-one-third-left=['<Control><Alt>d']
window-snap-one-third-right=['<Control><Alt>g']
window-snap-two-third-left=['<Control><Alt>e']
window-snap-two-third-right=['<Control><Alt>t']
window-swap-down=['<Control><Super>j']
window-swap-last-active=['<Super>Return']
window-swap-left=['<Control><Super>h']
window-swap-right=['<Control><Super>l']
window-swap-up=['<Control><Super>k']
window-toggle-always-float=['<Shift><Super>c']
window-toggle-float=['<Super>c']
workspace-active-tile-toggle=['<Shift><Super>w']

[org/gnome/shell/extensions/just-perfection]
accent-color-icon=false
accessibility-menu=true
activities-button=true
animation=1
background-menu=true
clock-menu=true
clock-menu-position=0
clock-menu-position-offset=0
controls-manager-spacing-size=0
dash=true
dash-icon-size=0
double-super-to-appgrid=true
keyboard-layout=true
osd=true
osd-position=0
panel=false
panel-in-overview=true
ripple-box=true
search=true
show-apps-button=true
startup-status=1
theme=false
top-panel-position=0
window-demands-attention-focus=false
window-maximized-on-create=false
window-picker-icon=true
window-preview-caption=true
window-preview-close-button=true

[org/gnome/shell/keybindings]
focus-active-notification=['<Super>n']
toggle-message-tray=['<Super>v', '<Super>m']

[org/gnome/nautilus/preferences]
default-folder-viewer='list-view'
